haven.server=game.havenandhearth.com
haven.errorurl=https://discord.com/api/webhooks/1539580301670617180/22lN3VVCjUtSwI1bvpAhcvYl_7Yo-Wh0TDomrPmQdjgR8aZRzYSqxLgN0MuuF-WyaiMG
haven.cachebase=http://game.havenandhearth.com/render/
haven.mapbase=http://game.havenandhearth.com/java/

haven.resurl=https://game.havenandhearth.com/res/
haven.screenurl=https://game.havenandhearth.com/mt/ss
haven.dynresurl=https://game.havenandhearth.com/mt/dynres/
haven.srvmon=https://game.havenandhearth.com/mt/srv-mon
haven.newsfeed=http://www.havenandhearth.com/forum/feed.php?mode=news
